### ISSUE TITLE
v0-alpha Metaissue

### ISSUE THREAD

**Issue by 3benknight** [JGCRI/foresight#30]
Issues to be resolved for the v0-alpha release:

- [x] Fix Line Chart misalignment. #24 
- [x] Fix Line Chart Data Error when filtering for Subcategories and Regions. #26 
- [x] Make queries smaller and visualization dependent. #25 
- [x] Make gauge values update closer to originally selected ranges when the selected range does not exist. #27 
- [x] Fix Gauge Values not showing correct percentage change. #31 
- [x] Declutter Dashboard Code. #29 
- [x] Fix Land Allocation y-axis. #32 
- [x] Remove Exponential Notation for small values. #33 
- [x] Move Bar Chart Settings to the top left corner. #34 
- [x] Replace Electricity and Water Consumption Parameters. #36 

Less critical quality of life changes:

- [x] Add more data to the URL. #28
